### ISSUE TITLE
Add field type for writing pad for signatures

### ISSUE THREAD

**Issue by nik10-mah** [OpenESignForms/openesignforms#173] opened 2016-07-15 08:53 UTC
Is it possible to have a field type Sign Writer which will display a writing pad on which user can sign a document using mouse drag and generated signature is saved as images in database or anywhere else.?

**Comment by OpenESignForms** [comment] 2016-07-17 00:06
This is not currently available, but is being tracked back on issue 67: https://github.com/OpenESignForms/openesignforms/issues/67

Note that such drawn signatures are no more legal, and they clearly are not like traditional handwritten signatures (just look at people's signatures on most pads) in that no handwriting expert will be able to show anything of value, and they are clearly less legible.

We have heard this request many times, but when it comes to paying to add it in, all of our customers have opted to go traditional as the value is not particularly high.  We are closing this as a duplicate of 67.

**Closed by OpenESignForms** 2016-07-17 00:06 UTC
Labels: duplicate, enhancement
